name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PROD_PATH }}
            echo -e "${{ secrets.PROD_ENV }}" > .env.production
            source ~/.zshrc
            git pull origin main
            yarn install
            pm2 kill
            NODE_OPTIONS="--max-old-space-size=1024" pm2 --name voz-y-cuento-api start "yarn start:api"
            pm2 save
